### ISSUE TITLE
LinearClassification pythonScript Parameter

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.text#1]
Exciting new toolkit! Looking at the LinearClassification operator, is there a reason we need the pythonScript parameter? 

Could we instead use an include directive in the info.xml of the toolkit to make sure that the pythonScript always gets included as part of the .sab file? https://www.ibm.com/support/knowledgecenter/SSCRJU_4.0.0/com.ibm.streams.dev.doc/doc/applicationbundle.html Thanks!

**Comment by markheger** [comment]
The pythonScript parameter of the LinearClassification operator is optional since by default the parameter references to the script in the com.ibm.streamsx.text toolkit.

The com.ibm.streamsx.text toolkit provides the python script in its etc directory and it is already included in the sab file when you build an application depending on the com.ibm.streamsx.text toolkit.
With the pythonScript parameter the user has the option to apply any project specific scripts without the need to change the toolkit files.

**Comment by Alex-Cook4** [comment]
@markheger We were running into a case where the python script wasn't actually being found despite the parameter not being set (using the default) when the bundle was run on a different host. Any thoughts?

**Comment by markheger** [comment]
Yes, the problem is that Streams 4.0 and 4.1 does not provide the method to retrieve the toolkit location.in a SPL function. Therefore Streams 4.0 and Streams 4.1 are handled like Streams 3.2 and need to take care about toolkit location and/or script location in a multi-host environment.
The following method has been introduced in Streams 4.2:
SPL::Functions::Utility::getToolkitDirectory("com.ibm.streamsx.text")
to get the toolkit location in a SPL function, e.g. in a composite.
The toolkit has a wrapper method generated at toolkit build time: SPL::rstring getToolkitPath() to handle the different behaviour in the different versions.
If you build the toolkit with Streams 4.2, then SPL::Functions::Utility::getToolkitDirectory("com.ibm.streamsx.text") is used. But if you build the toolkit in older Streams versions, then the absolute path of the toolkit location is inserted here.
The problem is not that the script is part of the sab file like in your first comment, the problem is to get the location inside a SPL composite. In a generic primitive operator it would be easier to retrieve the toolkit location, but in a SPL composite we have the situation as described above.

**Comment by Alex-Cook4** [comment]
Thank you @markheger. That clears it up and it's good to know about the introduction of the getToolkitDirectory function. Thanks.
